Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.define "client1"
  config.vm.define "gw1"
  config.vm.define "gw2"
  config.vm.define "client2"

  config.vm.define "cm"

end
